### ISSUE TITLE
Ar_Erase is not clearing arrays and seems to be leaving behind ?Unknown Element Type?

### ISSUE THREAD

**Issue by IntenseMute** [xNVSE/NVSE#113]
Ar_Erase is not clearing arrays and seems to be leaving behind ?Unknown Element Type?
This is occurring only in the new 6.2.6 release.

**Below is an example script:**
```
Array_Var MyArray
Let MyArray := Ar_Construct "Array"
Ar_Append MyArray, "My new string within the array."
Ar_Erase MyArray
Ar_Dump MyArray
```

**Below is the output of the Ar_Dump**
```
** Dumping Array #22 **
Refs: 1 Owner 0F: LeaveNoWitnesses.esp
[ 0.000000 ] : ?Unknown Element Type?
```

As you can see, using Ar_Erase still leaves it in the array and makes it show as ?Unknown Element Type?

**Comment by Demorome** [comment]
Should be fixed next version (or hotpatch probably). Thanks!
