### ISSUE TITLE
STEAM_Loader.dll Issue

### ISSUE THREAD

**Issue by Zanderat** [xNVSE/NVSE#125]
![New Bitmap Image (3)](https://user-images.githubusercontent.com/52495909/166684984-c73bc618-1375-471d-abc1-b527089f72e0.jpg)
 Been getting this with current version

**Comment by NCRTrooper** [comment]
How did you manage to get an error like this? In all my ears of modding this game, I've ever seen such an error.

**Comment by VishVadeva50** [comment]
Probably something to fix on your windows install or the game, xNVSE works fine assuming your downloads wasnt messed up.
If you use any AV refer to issue 122

**Comment by Zanderat** [comment]
Yes.  After I posted this, I saw the AV issue.  Turns out my AV had quarantined then steam_loader.  So most likely the same issue.

**Comment by NCRTrooper** [comment]
So we can close this issue then? 
![761697282323382282](https://user-images.githubusercontent.com/71110031/166803780-80c64cbc-aeb1-4c99-aa9d-261fc9ad12ab.png)

**Comment by VishVadeva50** [comment]
S6S if you are reading this... please!!!

**Comment by NCRTrooper** [comment]
What? Now all the shitposting will be in Zanderant's issue? Why Vish the Fish? Why?

**Comment by c6-dev** [comment]
woomzt

**Comment by NCRTrooper** [comment]
KARUT! Upload the NVTF source! PLEASE! I'M BEGGING YOU! STOP BEING LAZY FOR FIVE MINUTES!
