### ISSUE TITLE
Couldn't find NVSE DLL

### ISSUE THREAD

**Issue by zehDonut** [xNVSE/NVSE#13]
When I launch my game I get an error saying "Couldn't fine NVSE DLL  *\Fallout New Vegas\nvse_1_4ng.dll".

I'm using 5.1.6, so that file shouldn't be required any more, right?

**Comment by korri123** [comment]
German nogore version is not supported.

**Comment by zehDonut** [comment]
> German nogore version of Fallout New Vegas is not supported with xNVSE.

I'm using the Ultimate Edition, not the censored one.

**Comment by korri123** [comment]
You will still have to find a non-german FalloutNV.exe somewhere and replace your current one for xNVSE to work.

**Comment by zehDonut** [comment]
I'm on a new PC where no other version of new vegas has been installed before

**Comment by JIuBeP** [comment]
just install fallout 4gb patch.
