### ISSUE TITLE
Confusing debug message printed when RunScript finishes

### ISSUE THREAD

**Issue by Saxonis** [xNVSE/NVSE#146]
The message printed by

Console_Print("ran script, returned %s", runResult ? "true" : "false");

cannot be turned off and confuses players into thinking something is wrong in their game, whereas it only signifies a normal operation.

**Comment by NCRTrooper** [comment]
I tried telling my servant, Demorome about it, but that kid just doesn't listen. Although if you're using PrintC if your script, then remove it.

**Comment by Demorome** [comment]
Ah, I was looking for "returned false" string, woops.
Yeah, I'll remove that, and just make it return 1/0.
