### ISSUE TITLE
McAfee and NVSE_Steam_Loader.dll (resolved)

### ISSUE THREAD

**Issue by erigawn** [xNVSE/NVSE#150]
For whatever reason McAfee is quarantining the NVSE_Steam_Loader.dsl, thinking its a virus. I'm bringing it up because it may be fixeable on your end but I don't know. The only fix I have is to disable real-time scanning to play New Vegas though that raises some security risks. You also have to un-quarantine the item through McAfee.

*alternatively I can find a different security program if anyone has any recommendations*

**Comment by Masamune3210** [comment]
Unfortunately, it isnt solvable on either side of the equation really. The only people who can solve it are the AV vendors, and they don't seem to have much interest in doing so. Its called a false-positive, and the only way to get around it other than completely disabling your AV solution is to set the folder as excluded for scanning and hoping that the solution decides to actually honor what you ask

**Comment by RoyBatty64** [comment]
McAfee is a virus itself. It makes many unwanted system changes, and cannot be removed except by reformatting as it deeply imbeds itself into the boot loader and operating system and hides it's presence.

**Comment by blindhunter892** [comment]
I'm actually using 360 Security but its fine im still using it anyways

**Comment by EddieEldridge** [comment]
> _alternatively I can find a different security program if anyone has any recommendations_

Windows Defender (comes with Windows) and some common sense is more than enough these days.

**Comment by erigawn** [comment]
I have found a solution in whitelisting specifically the nvse_steam_loader.dll (not .dsl, thats my bad) under real-time scanning with Mcafee's programs. And it seems to ruin A-okay.

**Comment by Masamune3210** [comment]
hopefully its not ruining anything lol
