### ISSUE TITLE
GetNVSEVersion fails

### ISSUE THREAD

**Issue by eggboygamer** [xNVSE/NVSE#157]
GetNVSEVersion tells me
SCRIPTS: Script 'syswindowCompileandrun', line 1:
Script command "GetNVSE" not found.

I got 7zip I moved folders into game folder and I used the provided launcher and I reinstalled it on steam and the verification from the install video don't work :( (I'm on steam btw if that's relevant)

**Comment by onv-il** [comment]
life has many doors eggboy

**Comment by eggboygamer** [comment]
is this just a piece of wise cryptic advice or is this something I should understand?

**Comment by NCRTrooper** [comment]
That's just onvil being unhelpful as always.

**Comment by eggboygamer** [comment]
cool

**Comment by Demorome** [comment]
So is `nvse_1_4.dll`, etc. in the same folder as where `FalloutNV.exe` is found, or is it in a subfolder? Did you unpack the zip file?

**Comment by eggboygamer** [comment]
i used 7-zip and i moved all folders found inside nvse_6_2_8 to my Fallout New Vegas folder witch contains the FalloutNV application

**Comment by Demorome** [comment]
Are you launching the game from Steam, or the NVSE loader?

**Comment by eggboygamer** [comment]
im using the nvse_loader.exe

**Comment by NCRTrooper** [comment]
https://www.nexusmods.com/newvegas/mods/62552 Run 4GB Patcher and then launch the game from FalloutNV.exe. It'll load NVSE for you. No need for the NVSE loader.

**Comment by eggboygamer** [comment]
it worked, thanks for helping me out
