### ISSUE TITLE
Epic Games Support?

### ISSUE THREAD

**Issue by ZeLionOfWar** [xNVSE/NVSE#163]
It seems New Vegas has just been released on the Epic Games Store finally, and it's free as well. Any change the Script Extender will be updated in the future to work with the latest patch of the game that Epic applied?

**Comment by lStewieAl** [comment]
Not happening, it's a recompile so the offsets are totally different.

**Comment by ZeLionOfWar** [comment]
Alright, fair enough.

**Comment by HSJasperism** [comment]
Can't vouch for it, but there is currently an attempt to make things work https://www.nexusmods.com/newvegas/mods/81281
