### ISSUE TITLE
Lot of incompatible plugins, yet still loads

### ISSUE THREAD

**Issue by RedSnt** [xNVSE/NVSE#174]
Just sharing my concerns, because I didn't used to get messages about incompatibilities in MO2 (v2.4.4) before, and now I am.  
But everything still loads just fine, so just wanted to know what might've changed, because this happened as I upgraded from 6.2.7 to 6.3.4.  

Should I be worried? I just updated all of these (even accidentally overwrote lSteveAl Tweaks INI *sigh*), and still getting notified about this, and I can see on the "last modified" date that NVSE.log is getting updated for each run, so it's not like MO2 is reading the wrong log.

![image](https://github.com/xNVSE/NVSE/assets/6242718/a059e614-cf6a-49be-8bf1-53703baa88c3)
![image](https://github.com/xNVSE/NVSE/assets/6242718/39611777-7f84-4e1a-ade1-6c085c44dd39)
[nvse.log](https://github.com/xNVSE/NVSE/files/12904638/nvse.log)

**Comment by WallSoGB** [comment]
NVSE.log structure changed in 6.3.4 and MO2 doesn't know how to read it now, so it freaks out. Safe to ignore.

**Comment by RedSnt** [comment]
Thanks a bunch, was just worried for a second there. Now to keep going through lSteveAl Tweaks INI.. 😅

**Comment by AnyOldName3** [comment]
It'll make it easier to change our parsing if you can link the relevant commit (or even make a PR yourselves if you're keen - the relevant plugin's pretty simple https://github.com/ModOrganizer2/modorganizer-script_extender_plugin_checker/blob/master/src/ScriptExtenderPluginChecker.py).

Either way, the attached log and screenshot don't seem to match as it has to pull the `reported as incompatible during query` string out of the relevant line to print it. If the regex didn't match after the change, it wouldn't recognise it as a line mentioning a plugin and would ignore it, and if it matched but incorrectly, it'd spit out most of what it matched more-or-less verbatim, but there's no path for it to make up a reason for a plugin to fail, and last I checked, nothing caching the message from a past run.
