### ISSUE TITLE
Update 6.3.5 Crashes at fast travel

### ISSUE THREAD

**Issue by Just047** [xNVSE/NVSE#182]
Hello, thank you all for the years of continued work, myself and a few others have experienced crashes when attempting to fast travel since installing the newest update. I'll note I'm playing on steamdeck if that information is of any value. Below is my crash logger report. It's entirely possible that some other mods are causing this issue, but I still think it should be noted.

(Not Really) Cobb's Name Coiner (Works On My Machine Edition) (I'd Rather Be Playing Starfield Edition) version 4.5 beta 3 at 2024-01-25 22:47:28.7367264
If this file is empty, then your game didn't crash or something went so wrong even crash logger was useless! :snig:
Topmost stack module is NOT ALWAYS the crash reason! Exercise caution when speculating!

Exception C0000005 caught!

Thread: [FNV] Main

Calltrace:
Cannot create a copy of DbgHelp.dll, error: 0x00000005
0x0167F414 ==>            falloutnv (0x0093D7C7) : EntryPoint+0xFFFFFFFF
0x0167F690 ==>            falloutnv (0x0079802B) : EntryPoint+0xFFFFFFFF
0x0167F914 ==>            falloutnv (0x0079824C) : EntryPoint+0xFFFFFFFF
0x0167FA90 ==>            falloutnv (0x0070D36E) : EntryPoint+0xFFFFFFFF
0x0167FA98 ==>            falloutnv (0x0070283B) : EntryPoint+0xFFFFFFFF
0x0167FAA4 ==>            falloutnv (0x0086FD81) : EntryPoint+0xFFFFFFFF
0x0167FAFC ==>            falloutnv (0x0086ECBF) : EntryPoint+0xFFFFFFFF
0x0167FE80 ==>            falloutnv (0x0086B3E8) : EntryPoint+0xFFFFFFFF
0x0167FEA0 ==>    nvse_steam_loader (0x100021E4) : EntryPoint+0xFFFFFFFF
0x0167FF30 ==>            falloutnv (0x00ECC470) : EntryPoint+0xFFFFFFFF
0x0167FF48 ==>             kernel32 (0x1002AFD0) : EntryPoint+0xFFFFFFFF
0x0167FF5C ==>                ntdll (0x1005F8B7) : EntryPoint+0xFFFFFFFF
0x0167FFEC ==>                ntdll (0x100601D0) : RtlCreateUserThread+0x0

Registry:
REG |    VALUE   | DEREFERENCE INFO
eax | 0x00000000 | 
ebp | 0x0167F414 | 
ebx | 0x00000001 | 
ecx | 0x011DEAD0 | 
edi | 0xFFFFFFFE | 
edx | 0x011DEA3C | 
eip | 0x0093D7C7 | 
esi | 0x370F6D80 | 0x010780AC ==> Class: FOPipboyManager
esp | 0x0167F1EC | 

Stack:
 # |    VALUE   | DEREFERENCE INFO
 0 | 0x00000000 | 
 1 | 0x011DEA3C | 
 2 | 0x5920BAA0 | 
 3 | 0x00000001 | 
 4 | 0x3A0EA000 | 
 5 | 0x00000202 | 
 6 | 0x0167F9B4 | 
 7 | 0x00EF9C6C | 
 8 | 0xFFFFFFFF | 
 C | 0x32534140 | 0x010C2E7C ==> Class: BSScissorTriShape: Name: "Interface: TileImage"
14 | 0x32534140 | 0x010C2E7C ==> Class: BSScissorTriShape: Name: "Interface: TileImage"
16 | 0x32534140 | 0x010C2E7C ==> Class: BSScissorTriShape: Name: "Interface: TileImage"
2C | 0x325361A0 | 0x0109D454 ==> Class: NiTriShape: Name: "Interface: TileImage"
2E | 0x325361A0 | 0x0109D454 ==> Class: NiTriShape: Name: "Interface: TileImage"
6B | 0x0167F3E8 | 0x011F3374 ==> Global: TileValueIndirectTemp0X000FAF
6F | 0x370F6D80 | 0x010780AC ==> Class: FOPipboyManager
72 | 0x0167F3E8 | 0x011F3374 ==> Global: TileValueIndirectTemp0X000FAF
7E | 0x1A33EB40 | 0x0106F01C ==> Class: TileImage: Path: MapMenu/GLOW_BRANCH/MM_MainRect/MM_ButtonRect/MM_ButtonA
8E | 0x32533DC0 | 0x010C2E7C ==> Class: BSScissorTriShape: Name: "Interface: Text"
8F | 0x30344580 | 0x0109B5AC ==> Class: NiNode: failed to format
A6 | 0x32533CE0 | 0x010C2E7C ==> Class: BSScissorTriShape: Name: "Interface: TileImage"
A7 | 0x30344340 | 0x0109B5AC ==> Class: NiNode: Name: "MM_Highlight_CenterDot"
AB | 0x415E4480 | 0x01074D44 ==> Class: MapMenu: MenuMode: 1023, visible: 1, visibilityState : 0x1, TileMenu: Path: MapMenu
BF | 0x30344A00 | 0x0109B5AC ==> Class: NiNode: Name: "MM_MapHighlightBox"
CD | 0x30342240 | 0x0109B5AC ==> Class: NiNode: Name: "MM_Highlight_LRVert"
CE | 0x30344A00 | 0x0109B5AC ==> Class: NiNode: Name: "MM_MapHighlightBox"
CF | 0x30344A00 | 0x0109B5AC ==> Class: NiNode: Name: "MM_MapHighlightBox"
D6 | 0x30344A00 | 0x0109B5AC ==> Class: NiNode: Name: "MM_MapHighlightBox"
D7 | 0x30344B80 | 0x0109B5AC ==> Class: NiNode: Name: "MM_Highlight_ClipWindow"
EF | 0x3032F880 | 0x0109B5AC ==> Class: NiNode: Name: "MM_Tabline"
FD | 0x30328800 | 0x0109B5AC ==> Class: NiNode: Name: "Radio"
FE | 0x3032F880 | 0x0109B5AC ==> Class: NiNode: Name: "MM_Tabline"
FF | 0x3032F880 | 0x0109B5AC ==> Class: NiNode: Name: "MM_Tabline"

Memory:
MinimumWorkingSetSize:       32.00 MB
MaximumWorkingSetSize:       32.00 MB
PeakWorkingSetSize:           1.57 GB
WorkingSetSize:               1.56 GB
QuotaPeakPagedPoolUsage:         0 B
QuotaPagedPoolUsage:             0 B
QuotaPeakNonPagedPoolUsage:      0 B
QuotaNonPagedPoolUsage:          0 B
PageFaultCount:                  0 B
PagefileUsage:                1.32 GB
PeakPagefileUsage:            1.32 GB

Module bases:
0x3BF20000 - 0x3BF37000 ==> actorcausesavebloatfix,                                actorcausesavebloatfix
0x69840000 - 0x69885000 ==> advapi32,                                              advapi32
0x18FF0000 - 0x18FF9000 ==> alpha fixes,                                           alpha fixes
0x3BF40000 - 0x3BF6F000 ==> anhnvse,                                               anhnvse
0x6C900000 - 0x6C934000 ==> atl100,                                                atl100
0x5D390000 - 0x5D39B000 ==> avicap32,                                              avicap32
0x40100000 - 0x401A3000 ==> baseobjectswapper,                                     baseobjectswapper
0x18000000 - 0x18068000 ==> binkw32,                                               binkw32
0x3BF70000 - 0x3BF8A000 ==> climatecontrol,                                        climatecontrol
0x3BF90000 - 0x3BFB0000 ==> cloudupgrade,                                          cloudupgrade
0x684C0000 - 0x68523000 ==> combase,                                               combase
0x67BC0000 - 0x67D29000 ==> comctl32,                                              comctl32
0x69040000 - 0x6914F000 ==> comdlg32,                                              comdlg32
0x66FC0000 - 0x66FD6000 ==> compstui,                                              compstui
0x62C40000 - 0x62C69000 ==> concrt140,                                             concrt140
0x40560000 - 0x405D8000 ==> crashlogger,                                           crashlogger
0x3BFB0000 - 0x3BFD0000 ==> cum,                                                   cum
0x10000000 - 0x101C2000 ==> d3d9,                                                  d3d9
0x001E0000 - 0x001EE000 ==> d3dx9_38,                                              d3dx9_38
0x59000000 - 0x591FF000 ==> d3dx9_43,                                              d3dx9_43
0x70000000 - 0x7006A000 ==> dbghelp,                                               dbghelp
0x6A940000 - 0x6A977000 ==> devenum,                                               devenum
0x61FC0000 - 0x62015000 ==> dinput8,                                               dinput8
0x6ECC0000 - 0x6ECD6000 ==> dnsapi,                                                dnsapi
0x3BFD0000 - 0x3BFE7000 ==> dof-fix,                                               dof-fix
0x01D70000 - 0x01DD7000 ==> dsound,                                                dsound
0x401B0000 - 0x401D4000 ==> dynamicpipboylight,                                    dynamicpipboylight
0x40DE0000 - 0x40E21000 ==> dynamicreflections,                                    dynamicreflections
0x401E0000 - 0x401F9000 ==> engineoptimizations,                                   engineoptimizations
0x40E30000 - 0x40E54000 ==> externalemittancefix,                                  externalemittancefix
0x00400000 - 0x0147B000 ==> falloutnv,                                             falloutnv
0x40E60000 - 0x40E7B000 ==> fogculling,                                            fogculling
0x6DA80000 - 0x6DB0A000 ==> gdi32,                                                 gdi32
0x59620000 - 0x596B7000 ==> gdiplus,                                               gdiplus
0x40E80000 - 0x40E96000 ==> hdpipboy,                                              hdpipboy
0x40EA0000 - 0x40EB8000 ==> hdr-patch,                                             hdr-patch
0x71080000 - 0x7108F000 ==> hid,                                                   hid
0x40EC0000 - 0x40ED9000 ==> highresbloom,                                          highresbloom
0x40EE0000 - 0x40EF6000 ==> highreslocalmaps,                                      highreslocalmaps
0x40F00000 - 0x40F18000 ==> highreswaterdepth,                                     highreswaterdepth
0x67500000 - 0x6751F000 ==> imm32,                                                 imm32
0x40F20000 - 0x40F89000 ==> improved_console,           NVSE plugin version:    3, improved_console
0x40F90000 - 0x40FB6000 ==> improvedlightingshaders,                               improvedlightingshaders
0x646C0000 - 0x646F6000 ==> iphlpapi,                                              iphlpapi
0x59200000 - 0x59283000 ==> jip_nvse,                   NVSE plugin version: 5721, jip_nvse
0x59290000 - 0x592E4000 ==> johnnyguitar,               NVSE plugin version:  498, johnnyguitar
0x7B600000 - 0x7B663000 ==> kernel32,                                              kernel32
0x7B000000 - 0x7B2AE000 ==> kernelbase,                                            kernelbase
0x592F0000 - 0x59369000 ==> knvse,                                                 knvse
0x01E00000 - 0x01F33000 ==> libvorbis,                                             libvorbis
0x01DE0000 - 0x01DFE000 ==> libvorbisfile,                                         libvorbisfile
0x3BFF0000 - 0x3BFF9000 ==> lod fixes,                                             lod fixes
0xF5F80000 - 0xF6230000 ==> lsteamclient,                                          lsteamclient
0x40FC0000 - 0x40FF2000 ==> mcm,                                                   mcm
0x6A500000 - 0x6A570000 ==> mfplat,                                                mfplat
0x66280000 - 0x6628C000 ==> midimap,                                               midimap
0x593A0000 - 0x593A7000 ==> mlf,                                                   mlf
0x6ACC0000 - 0x6ACEC000 ==> mmdevapi,                                              mmdevapi
0x593B0000 - 0x593D6000 ==> moonlightnvse,                                         moonlightnvse
0x712C0000 - 0x712E0000 ==> mpr,                                                   mpr
0x01D40000 - 0x01D62000 ==> msacm32,                                               msacm32
0x6C540000 - 0x6C568000 ==> msdmo,                                                 msdmo
0x6C980000 - 0x6CA6F000 ==> msvcp140,                                              msvcp140
0x65680000 - 0x65733000 ==> msvcrt,                                                msvcrt
0x5D360000 - 0x5D385000 ==> msvfw32,                                               msvfw32
0x593E0000 - 0x593F7000 ==> muzzleflashfix,                                        muzzleflashfix
0x6F6C0000 - 0x6F6CC000 ==> nsi,                                                   nsi
0x7BC00000 - 0x7BCAF000 ==> ntdll,                                                 ntdll
0x02DB0000 - 0x02DC4000 ==> nvhr_avx2,                                             nvhr_avx2
0x40410000 - 0x40560000 ==> nvse_1_4,                                              nvse_1_4
0x59400000 - 0x59406000 ==> nvse_console_autocomplete,                              nvse_console_autocomplete
0x59410000 - 0x59478000 ==> nvse_console_clipboard,     NVSE plugin version:    2, nvse_console_clipboard
0x59480000 - 0x5949C000 ==> nvse_enhanced_camera_sink_fix,                              nvse_enhanced_camera_sink_fix
0x594D0000 - 0x594F5000 ==> nvse_enhancedcamera,                                   nvse_enhancedcamera
0x07280000 - 0x072AD000 ==> nvse_steam_loader,                                     nvse_steam_loader
0x59530000 - 0x59620000 ==> nvse_stewie_tweaks,         NVSE plugin version:  895, nvse_stewie_tweaks
0x596C0000 - 0x596EF000 ==> nvtf,                                                  nvtf
0x66380000 - 0x664BE000 ==> ole32,                                                 ole32
0x62500000 - 0x62639000 ==> oleaut32,                                              oleaut32
0x596F0000 - 0x59720000 ==> onetweak,                                              onetweak
0x59720000 - 0x59738000 ==> pipboyshadingfix,                                      pipboyshadingfix
0x59740000 - 0x5975B000 ==> preferredpathingcombatfix,                              preferredpathingcombatfix
0x5D3A0000 - 0x5D3D3000 ==> propsys,                                               propsys
0x63900000 - 0x6390A000 ==> psapi,                                                 psapi
0x64900000 - 0x649E7000 ==> quartz,                                                quartz
0x65480000 - 0x65513000 ==> rpcrt4,                                                rpcrt4
0x6B140000 - 0x6B151000 ==> rtworkq,                                               rtworkq
0x6BBC0000 - 0x6BBEE000 ==> sechost,                                               sechost
0x6AEC0000 - 0x6AF48000 ==> setupapi,                                              setupapi
0x667C0000 - 0x667DA000 ==> shcore,                                                shcore
0x71400000 - 0x71D61000 ==> shell32,                                               shell32
0x66080000 - 0x660DD000 ==> shlwapi,                                               shlwapi
0x59760000 - 0x5989A000 ==> showoffnvse,                                           showoffnvse
0x598A0000 - 0x598F0000 ==> sound_extender,                                        sound_extender
0x5B2B0000 - 0x5B3ED000 ==> steam,                                                 steam
0x3B400000 - 0x3B41D000 ==> steam_api,                                             steam_api
0x59FB0000 - 0x5B2A7000 ==> steamclient,                                           steamclient
0x598F0000 - 0x59A1E000 ==> supnvse,                                               supnvse
0x59A20000 - 0x59A5D000 ==> ttw_nvse,                   NVSE plugin version:  332, ttw_nvse
0x6AAC0000 - 0x6ABA0000 ==> ucrtbase,                                              ucrtbase
0x59A60000 - 0x59A6B000 ==> ui_organizer,               NVSE plugin version:  230, ui_organizer
0x68880000 - 0x68A3E000 ==> user32,                                                user32
0x02E90000 - 0x02FE3000 ==> usvfs_x86,                                             usvfs_x86
0x70D80000 - 0x70DB7000 ==> uxtheme,                                               uxtheme
0x643C0000 - 0x643CC000 ==> vcruntime140,                                          vcruntime140
0x66640000 - 0x6664D000 ==> version,                                               version
0x59B00000 - 0x59B09000 ==> viewmodelshakefix,                                     viewmodelshakefix
0x59B10000 - 0x59B16000 ==> weapon_lag_fix,                                        weapon_lag_fix
0x64A80000 - 0x64ABC000 ==> win32u,                                                win32u
0x61EE0000 - 0x61F12000 ==> winealsa,                                              winealsa
0x6BFC0000 - 0x6C04A000 ==> winegstreamer,                                         winegstreamer
0x63E40000 - 0x63E70000 ==> winepulse,                                             winepulse
0x6FA80000 - 0x6FABE000 ==> winevulkan,                                            winevulkan
0x6BB40000 - 0x6BB6A000 ==> winex11,                                               winex11
0x6C100000 - 0x6C188000 ==> wininet,                                               wininet
0x6F240000 - 0x6F308000 ==> winmm,                                                 winmm
0x64180000 - 0x641B2000 ==> winspool,                                              winspool
0x01940000 - 0x0196A000 ==> ws2_32,                                                ws2_32
0x69BC0000 - 0x69BD0000 ==> wsock32,                                               wsock32
0x6CD40000 - 0x6CD52000 ==> xinput1_3,                                             xinput1_3
0x59B20000 - 0x59B88000 ==> yui,                                                   yui

GAME CRASHED AT INSTRUCTION Base+0x0053D7C7 IN MODULE: falloutnv
Please note that this does not automatically mean that that module is responsible. It may have been supplied bad data or
program state as the result of an issue in the base game or a different DLL.

**Comment by Demorome** [comment]
Woops yeah that's on me, I'll fix it in short order and replace the uploaded versions.

**Comment by AVeryUncreativeUsername** [comment]
Demorome! You need to be more careful! NVSE is the foundation of FNV modding. One slight crack in that foundation and it can all crumbling down! So just remember not to be so karut about things.

**Comment by auser1337** [comment]
:pepeglare:

**Comment by Demorome** [comment]
Fixed version is out, sorry about that.

**Comment by Just047** [comment]
Thank you #Himzers
