### ISSUE TITLE
Algohol Function V3Normalize "Expected end of line." compile error in GECK

### ISSUE THREAD

**Issue by Splayn3D** [xNVSE/NVSE#19]
Hello and thank you all for this awesome project!
I was playing around with coding ideas and got an "Expected end of line." error while compiling using the V3Normalize function in a script.

This is the only algohol function that wont let me compile my script.

I'm very new to Fallout scripting so I don't know that I'm just overlooking something..

Test script used:

	scriptName SPLTestScript01

	float fEulX
	float fEulY
	float fEulZ

	Begin onActivate
		set fEulX to 0.2547
		set fEulY to 1.9988
		set fEulZ to 25.2234

		V3Normalize "fEulX" "fEulY" "fEulZ" fEulX fEulY fEulZ 		;End of line error
		;V3Norm "fEulX" "fEulY" "fEulZ" fEulX fEulY fEulZ 		;Same end of line error

		Print "Result of the floats: X: " + $fEulX + ", Y: " + $fEulY + ", Z:" + $fEulZ

	End

**Comment by korri123** [comment]
Seems like that function had the wrong parameter types and you're the first to notice. Thanks for the report, will be fixed.

**Comment by korri123** [comment]
Here's a fixed version if you need to use the function before we update:
[nvse_prerelease.zip](https://github.com/xNVSE/NVSE/files/5992071/nvse_prerelease.zip)
