### ISSUE TITLE
Crash during loading

### ISSUE THREAD

**Issue by PudducQ** [xNVSE/NVSE#196]
Hello Everybody,

I have the following issue:
FNV crashed during loading and command screen indicate: 
Hook_DirectInput8Create_Execute
Cannot write call hook at adress 0x785087; another hook make it longer a fonction call.

![Capture d'écran 2024-05-20 185805](https://github.com/xNVSE/NVSE/assets/170360352/551f2403-8824-4627-bd00-b59a9f765069)

[CrashLogger.2024-05-20-17-03-54.log](https://github.com/xNVSE/NVSE/files/15380591/CrashLogger.2024-05-20-17-03-54.log)

Please help

BR,

PudducQ

**Comment by Demorome** [comment]
Hello, simply update ShowOff to version 1.80, this is a common issue if you somehow downloaded the older 1.71 version.

**Comment by PudducQ** [comment]
Thanks a lot

**Comment by AVeryUncreativeUsername** [comment]
I really wish Nexus would let us delete the old ShowOff files. Their stupid policy of forced file retention for the sake of their stupid collections causes nothing but problems and headaches.
