### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by swedneck** [xNVSE/NVSE#22]
You should get permission from all contributors to add an open license to this, so people can legally contribute!

**Comment by NCRTrooper** [comment]
I'd love an open license because NVSE licensing fees are ridiculous! $150,000 per function. An open license would be great as we could add to NVSE and avoid those unlicensed plugins.

**Comment by swedneck** [comment]
What are you on about? Code needs a license to be legally used and modified, see https://choosealicense.com/

**Comment by RoyBatty64** [comment]
The code has a license the same as it always did. All xSE plugins for all Bethesda games have the same license.

**Comment by swedneck** [comment]
Then that license should ideally be added to this repo in the form of a `LICENSE` file, as is standard.

**Comment by swedneck** [comment]
Ah, i found the license in a file buried in a folder, i'll make a PR to copy it to a standard `LICENSE` file!

**Comment by korri123** [comment]
That's actually for the commons library, afaik xSE was always unlicensed. I'll speak to Ian at some point so that a license can be added.

**Comment by swedneck** [comment]
Oh, i'll hold off on the PR then. Thanks for looking into it!

FWIW i highly recommend using a standard open source license, CC-BY-SA should follow the spirit of the license in that file, even though it's not usually used for code.

**Comment by PopeRigby** [comment]
Any updates on this?

**Comment by korri123** [comment]
Not up to us but Ian of the xSE team (SKSE maintainer) unfortunately.

**Comment by PopeRigby** [comment]
@korri123 Is Ian open to discussing this sort of thing?

**Comment by korri123** [comment]
You'd be better off asking him. His email is on the silverlock.org website.

**Comment by PopeRigby** [comment]
Alright, thank you.
