### ISSUE TITLE
X mod breaks since xNVSE 6.0.7 release.

### ISSUE THREAD

**Issue by rdok** [xNVSE/NVSE#26]
### Bug Report

[Flashlight NVSE][flashlight_link] has been broken since the [xNVSE 6.0.7][nvse_link_607] release.  With 20K+ endorsements, makes it a popular mod.  
Reverting to [xNVSE 6.0.6][nvse_link_606] mod works as expected.  
No relevant logs were found. 

*Expected Behavior*
- Given I am a user that has installed said mod
- When I attempt to enable the flashlight, in-game, using the default key `J`
- Then I should see the flashlight being enabled
- And I should hear a noise indicating flashlight being enabled

*Actual Behavior*
- Nothing happens 

***

### Temporary solution
As long as no other new mods are installed that rely on `>= NVSE 6.0.7` should be OK to run with old version. 

***

### Debugging attempt
- Install [Flashlight NVSE][flashlight_link]. Extract fomod, and install it directly as a file.
	- This was the only way to achieve all green checkmarks on installation GUI
- On conflict resolution, load it after oHUD; this resolves an issue with relevant mod throwing an in-game popup error when attempting to access it on [The Mod Configuration Menu][tmom_link]
- Add Flashlight head item quickly through console command: 
	- `player.additem {add_your_mod_index_here}004507`
	- Use Vortex -> Plugins -> Filter Flashlight -> See ModIndex Column to find your `{add_your_mod_index_here}`
- Enable NVSE Logs:
```
[Logging]
EnableGameErrorLog=1
[RELEASE]
LogLevel=5
```

At this point, after multiple attempts to enable flashlight with relevant hotkey, I was unable to find any relevant error logs.

> Remember to disable logs to speed up game again

[flashlight_link]: https://www.nexusmods.com/newvegas/mods/39968
[nvse_link_606]: https://github.com/xNVSE/NVSE/releases/tag/6.0.6
[nvse_link_607]: https://github.com/xNVSE/NVSE/releases/tag/6.0.7
[tmom_link]: https://www.nexusmods.com/newvegas/mods/42507

**Comment by korri123** [comment]
Will be fixed in the next update, thanks for the report.

**Comment by erafox2** [comment]
OMG can you fix that ... is one of most popular mods.. also theres no other flahslight mod

**Comment by korri123** [comment]
Fixed in 6.0.9
