### ISSUE TITLE
Script Extender Log Reports Incompatible Plugins

### ISSUE THREAD

**Issue by Cinnaspice** [xNVSE/NVSE#30]
Mod Organizer2 (for Fallout NV) is reporting "You have one or more script extender plugins which failed to load!

The failed plugins are:
  • NVTF version 9 (NVTF.dll, NVTF - New Vegas Tick Fix) reported as incompatible during query.
  • OneTweak version 1 (OneTweak.dll, OneTweak for FNV) reported as incompatible during query."

But I haven't changed any of the three installs - xNVSE, NVTF, nor OneTweak. They were working fine before. It was sudden and very disconcerting. Please advise. Thank you.

**Comment by korri123** [comment]
Not an issue with xNVSE, you are most likely missing DirectX runtime libraries or VC++ redists for these plugins, or external software like antivirus is blocking the DLLs.

https://www.microsoft.com/en-us/download/details.aspx?id=8109
https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads
