### ISSUE TITLE
NOT AN ISSUE!!!! Just a comment

### ISSUE THREAD

**Issue by seriousgamer42** [xNVSE/NVSE#32]
NOT AN ISSUE!!!!
There's no need to install 7-zip or WinRar, just goto [https://extract.me/](url)
NOT AN ISSUE!!!!

**Comment by Chaython** [comment]
Developer could just save as a self extracting or a zip, but he doesn't want to.

**Comment by llde** [comment]
@Chaython  7-Zip is the superior Standard. [STACCE](https://www.facebook.com/romeismore/posts/-stacce-is-a-kind-of-state-of-mind-to-be-used-as-an-acceptance-of-a-negative-but/1156962847785164/)!

**Comment by Chaython** [comment]
I don't get why you said stacce at the end.
Anyways, as I said, the developer could make the .7z self extracting. It was my initial suggestion, so I don't know why you responded seeming to presume I dislike 7-Zip.
Anyways ZSTD is the most superior. Thank your Facebook overlords.
