### ISSUE TITLE
"someNumber % 0" causes a crash.

### ISSUE THREAD

**Issue by Demorome** [xNVSE/NVSE#35]
Tested on stable release v6.0.9 and on latest beta.

Happens in scripts (quest / UDF) as well as in console.

What's weird is that the code does seem to avoid performing `_ % 0` correctly. I just stepped through the latest beta code and it correctly went to `context->Error("Division by zero");` (in `Eval_Integer()`).

Meanwhile, ` _ /= 0` and `_ / 0` don't cause a crash and just report the error in console. But they seem to have more or less the same safety mechanism (`if (r != 0)`)...

Here's the error as reported in VC (while debugging the latest beta): 
![image](https://user-images.githubusercontent.com/69116996/120812268-3645bf80-c523-11eb-850b-ad3907e50df6.png)

I only found out because I was trying to add `%=` and that was also causing a similar crash 😅 

Edit: I said "latest beta", but because of some Git App weirdness the latest version I could test on was the merged version of "Ar_DumpF" branch.

**Comment by korri123** [comment]
Thanks, fixed
