### ISSUE TITLE
Geck extender behavior?

### ISSUE THREAD

**Issue by Tommack63** [xNVSE/NVSE#38]
I downloaded 6.1.0 and not sure about this but the latest Geck extender is tossing up modal message boxes with "Error: current script stack is empty." when in any quest examining topics. It never did that before.

**Comment by korri123** [comment]
Could you post the script or .esp? That's not supposed to happen!

**Comment by korri123** [comment]
Thanks for the report! fixing it now...

**Comment by korri123** [comment]
Fixed, thanks. I updated nvse_1_4_editor.dll in xNVSE 6.1.1 release.

**Comment by Tommack63** [comment]
Thanks
