### ISSUE TITLE
NVAC Re[orting as Incompatible?

### ISSUE THREAD

**Issue by Zanderat** [xNVSE/NVSE#4]
NVAC seems to be incompatible with the new version of NVSE.  [quote]_plugin C:\GOG Games\Fallout New Vegas\Data\NVSE\Plugins\\nvac.dll (00000001 NVAC - New Vegas Anti Crash 07050000) reported as incompatible during query_[/quote]

**Comment by korri123** [comment]
NVAC is not incompatible with xNVSE, there is something in your computer that's blocking it from loading. Check if you are missing any redistributables or if an antivirus is blocking it or if you have RivaTuner or Afterburner running, which may cause problems.
