### ISSUE TITLE
DebugTextCreate Function is no longer functional since 6.1.2

### ISSUE THREAD

**Issue by KirkH420** [xNVSE/NVSE#41]
Before the update, this function was able to print an On Screen Display at a specified location. There are several other similar functions to go with it. At the current time, the console will accept this function but do nothing, nor will it work from a script.

A test in the console should actually cause On Screen Text to become visible:
DebugTextCreate "MyDebugText1" 100 100 "My Text"

**Comment by korri123** [comment]
This function is not part of xNVSE but SUP NVSE (https://github.com/TommInfinite/SUP-NVSE-PLUGIN). I regardless tested the function and came to the conclusion that it broke with SUP's update from 2 to 3, not xNVSE's update.
