### ISSUE TITLE
Missed versioning one of the DDL's again?

### ISSUE THREAD

**Issue by Tommack63** [xNVSE/NVSE#44]
Just noted... the steam ddl version does not match in 6.1.4 to the others, not that it really matter but my is funny my mod manager thinks the archive is for 6.1.3 when it's not, ( must be stupid to go by the last file? Anyway keeps telling a new version in available)... Iikely i'll just edit the version info myself. ;)

**Comment by korri123** [comment]
I did it this way because these DLLs get flagged as false positives by anti-virus each time they get rebuilt with a new version, so I temporarily used old version of these files until Microsoft finishes whitelisting them from Defender, then I will switch them out.

**Comment by Tommack63** [comment]
Oh okay, makes sense and thanks.
