### ISSUE TITLE
NVSE won't launch properly

### ISSUE THREAD

**Issue by xnoble2x** [xNVSE/NVSE#5]
I have placed the NVSE .exe and .dll in the folder with the NV launcher but it does not launch when i run new vegas, nor does it run when i use the NVSE loader, I don't get any errors it just doesn't seem to run as when i run the command GetNVSEVersion it says that is not a valid command. Any help in figuring out why this is the case would be appreciated.

**Comment by korri123** [comment]
Go to add or remove programs and post a screenshot of the VC++ redistributables you have installed.

**Comment by xnoble2x** [comment]
![Capture](https://user-images.githubusercontent.com/66567247/83976524-e0562180-a8a6-11ea-82e7-0a5aa02d80b4.PNG)

**Comment by korri123** [comment]
Okay, this looks fine. Are you sure you placed all the files, including the nvse_steam_loader.dll file in the folder? Also, did you use [the right 4GB patcher](https://www.nexusmods.com/newvegas/mods/62552) when patching the game?

Also, if these files exists, send your nvse.log, nvse_loader.log and nvse_steam_loader.log (if you're using steam), located in the base Fallout NV game folder.

**Comment by xnoble2x** [comment]
Ok so I found the problem, i guess when i downloaded the file from github it somehow didn't download the nvse_steam_loader.dll, redownloading and adding that file in seems to have fixed it.
Thanks for the help mate!

**Comment by RandyAlvarez0** [comment]
Im having the same problem only my game just doesn't want to even startup with the nvse_loader. I have the nvse_steam_loader, pretty sure I have the Microsoft Visual C++ Drivers because the game worked before I decided to install a new ENB and messed the game up.
