### ISSUE TITLE
NVSE Plugin Example not compiling in new versions

### ISSUE THREAD

**Issue by IlnurGabidullin** [xNVSE/NVSE#51]
NVSE PE not compiling in 6.16 and 6.17 versions of nvse.(in version 6.15 compiles. I checked)
Visual studio 2019 throws an error:
GameAPI.cpp(2389,43): error C2653: 'NVSEVarType': is not a class or namespace name
GameAPI.cpp(2389,56): error C2065: 'kVarType_String': undeclared identifier
GameAPI.cpp(2389,4): error C3861: 'AddToGarbageCollection': identifier not found
3 Errors in:
if (!scriptVar->ref || scriptVar->ref == script->quest || scriptVar->ref == refr) // if not an external script
			AddToGarbageCollection(eventList, var, NVSEVarType::kVarType_String);
if i comment it, declared 'NVSEVarType', 'kVarType_String, 'AddToGarbageCollection' or include ScriptTokens.h
Visual studio 2019 throws an another errors:
`
GameAPI.obj : error LNK2019: unresolved external symbol "public: __thiscall ScriptParsing::ScriptIterator::ScriptIterator(class Script *,unsigned char *)" (??0ScriptIterator@ScriptParsing@@QAE@PAVScript@@PAE@Z) referenced in function "bool __cdecl ExtractSetStatementVar(class Script *,struct ScriptEventList *,void *,double *,bool *,unsigned long const *,unsigned char *,class TESObjectREFR *)" (?ExtractSetStatementVar@@YA_NPAVScript@@PAUScriptEventList@@PAXPANPA_NPBKPAEPAVTESObjectREFR@@@Z)`

GameAPI.obj : error LNK2019: unresolved external symbol "public: __thiscall ScriptParsing::SetToStatement::SetToStatement(class ScriptParsing::ScriptIterator const &)" (??0SetToStatement@ScriptParsing@@QAE@ABVScriptIterator@1@@Z) referenced in function "bool __cdecl ExtractSetStatementVar(class Script *,struct ScriptEventList *,void *,double *,bool *,unsigned long const *,unsigned char *,class TESObjectREFR *)" (?ExtractSetStatementVar@@YA_NPAVScript@@PAUScriptEventList@@PAXPANPA_NPBKPAEPAVTESObjectREFR@@@Z)
and 
`
GameAPI.obj : error LNK2019: unresolved external symbol "void __cdecl AddToGarbageCollection(struct ScriptEventList *,struct ScriptLocal *,enum NVSEVarType)" (?AddToGarbageCollection@@YAXPAUScriptEventList@@PAUScriptLocal@@W4NVSEVarType@@@Z) referenced in function "bool __cdecl ExtractSetStatementVar(class Script *,struct ScriptEventList *,void *,double *,bool *,unsigned long const *,unsigned char *,class TESObjectREFR *)" (?ExtractSetStatementVar@@YA_NPAVScript@@PAUScriptEventList@@PAXPANPA_NPBKPAEPAVTESObjectREFR@@@Z)`

**Comment by IlnurGabidullin** [comment]
I solved the problem by removing "ExtractSetStatementVar"

**Comment by IlnurGabidullin** [comment]
I solved it by change
from

> 
> bool ExtractSetStatementVar(Script *script, ScriptEventList *eventList, void *scriptDataIn, double *outVarData, bool *makeTemporary, const UInt32 *opcodeOffsetPtr, UInt8 *outModIndex, TESObjectREFR* refr)
> {
> 	auto *scriptData = static_cast<UInt8 *>(scriptDataIn) + *opcodeOffsetPtr;
> 	auto* backPtr = scriptData - 5;
> 	if (*backPtr != 'X')
> 		return false;
> 
> 	if (*(backPtr - 3) == 'r')
> 		backPtr -= 3;
> 
> 	if (*(backPtr - 9) == 'r')
> 		backPtr -= 13;
> 	else
> 		backPtr -= 10;
> 	
> 	auto* statementStart = backPtr;
> 	if (*statementStart != static_cast<UInt8>(ScriptParsing::ScriptStatementCode::SetTo)) // make sure `set ... to` and not `if ...`
> 		return false;
> 
> 	const ScriptParsing::ScriptIterator iterator(script, statementStart);
> 	const auto statementCtx = ScriptParsing::SetToStatement(iterator);
> 	if (statementCtx.error || !statementCtx.toVariable || statementCtx.toVariable->error)
> 		return false;
> 
> 	if (auto* scriptVar = dynamic_cast<ScriptParsing::ScriptVariableToken*>(statementCtx.toVariable.get()))
> 	{
> 		ScriptLocal *var = eventList->GetVariable(scriptVar->varInfo->idx);
> 		if (!var)
> 			return false;
> 		*outModIndex = scriptVar->script->GetModIndex();
> 		*outVarData = var->data;
> 		if (!scriptVar->ref || scriptVar->ref == script->quest || scriptVar->ref == refr) // if not an external script
> 			AddToGarbageCollection(eventList, var, NVSEVarType::kVarType_String);
> 	}
> 	else if (auto* globalVar = dynamic_cast<ScriptParsing::GlobalVariableToken*>(statementCtx.toVariable.get()))
> 	{
> 		*outModIndex = globalVar->global->GetModIndex();
> 		*outVarData = globalVar->global->data;
> 	}
> 	else
> 		return false;
> 	*makeTemporary = false;
> 	return true;
> }






to





> #ifdef NVSE_CORE
> bool ExtractSetStatementVar(Script *script, ScriptEventList *eventList, void *scriptDataIn, double *outVarData, bool *makeTemporary, const UInt32 *opcodeOffsetPtr, UInt8 *outModIndex, TESObjectREFR* refr)
> {
> 	auto *scriptData = static_cast<UInt8 *>(scriptDataIn) + *opcodeOffsetPtr;
> 	auto* backPtr = scriptData - 5;
> 	if (*backPtr != 'X')
> 		return false;
> 
> 	if (*(backPtr - 3) == 'r')
> 		backPtr -= 3;
> 
> 	if (*(backPtr - 9) == 'r')
> 		backPtr -= 13;
> 	else
> 		backPtr -= 10;
> 	
> 	auto* statementStart = backPtr;
> 	if (*statementStart != static_cast<UInt8>(ScriptParsing::ScriptStatementCode::SetTo)) // make sure `set ... to` and not `if ...`
> 		return false;
> 
> 	const ScriptParsing::ScriptIterator iterator(script, statementStart);
> 	const auto statementCtx = ScriptParsing::SetToStatement(iterator);
> 	if (statementCtx.error || !statementCtx.toVariable || statementCtx.toVariable->error)
> 		return false;
> 
> 	if (auto* scriptVar = dynamic_cast<ScriptParsing::ScriptVariableToken*>(statementCtx.toVariable.get()))
> 	{
> 		ScriptLocal *var = eventList->GetVariable(scriptVar->varInfo->idx);
> 		if (!var)
> 			return false;
> 		*outModIndex = scriptVar->script->GetModIndex();
> 		*outVarData = var->data;
> 		if (!scriptVar->ref || scriptVar->ref == script->quest || scriptVar->ref == refr) // if not an external script
> 			AddToGarbageCollection(eventList, var, NVSEVarType::kVarType_String);
> 	}
> 	else if (auto* globalVar = dynamic_cast<ScriptParsing::GlobalVariableToken*>(statementCtx.toVariable.get()))
> 	{
> 		*outModIndex = globalVar->global->GetModIndex();
> 		*outVarData = globalVar->global->data;
> 	}
> 	else
> 		return false;
> 	*makeTemporary = false;
> 	return true;
> }
> #endif




(I added #ifdef)

**Comment by IlnurGabidullin** [comment]
I reopen issue since it needs to be solved in a normal way

**Comment by korri123** [comment]
Thanks, should be fixed now.
