### ISSUE TITLE
Game froze after installed the latest NVSE

### ISSUE THREAD

**Issue by Lacc1986** [xNVSE/NVSE#54]
I just updated my game with the latest release of NVSE and right after I got into the main menu I started loading up my latest save game when I click to continue the game froze but the music still going on.  I've read some issues with scripts and after I tried to re-install one of the previous releases but in that case my game crash after I tried loading any of my saves.

**Comment by korri123** [comment]
Test with this beta release (dropped in Fallout New Vegas folder):
[nvse_1_4.zip](https://github.com/xNVSE/NVSE/files/6911976/nvse_1_4.zip)

**Comment by Lacc1986** [comment]
It helped me load my save but the game froze while i want to go from a cell to another one (infinite loading screen), thank you for the help btw.

**Comment by korri123** [comment]
Infinite loading screen is not related to NVSE. Try this: https://www.nexusmods.com/newvegas/mods/70964?tab=posts

**Comment by Lacc1986** [comment]
I have this wee app even my loading is froze after I click on "load". 
[Save 122   Lacc  El Casino Ballroom  28 58 13.zip](https://github.com/xNVSE/NVSE/files/6913461/Save.122.Lacc.El.Casino.Ballroom.28.58.13.zip)
Well I can give u my save file for testing.

**Comment by korri123** [comment]
I need the .nvse cosave file.

**Comment by Lacc1986** [comment]
Here you go,
[Save 122   Lacc  El Casino Ballroom  28 58 13.zip](https://github.com/xNVSE/NVSE/files/6914912/Save.122.Lacc.El.Casino.Ballroom.28.58.13.zip)
 mate.

**Comment by Lacc1986** [comment]
The new version is working smoothly now. Cheers mate.
