### ISSUE TITLE
NVSE Couldn't Inject DLL

### ISSUE THREAD

**Issue by NicolaiPizzaGuy** [xNVSE/NVSE#63]
Trying to install xNVSE on a fresh install of New Vegas (GOG edition) but running into an error when attempting to run the NVSE Loader. When I run the loader as admin the command prompt pops up as it normally would, but then I receive a "Couldn't Inject DLL" error. After this I'm able to successfully run the launcher, which launches New Vegas without issue, but NVSE isn't being detected as the "getnvseversion" command throws back: 

"SCRIPTS: Script 'SysWindowCompileAndRun', line 1: 
Script command 'GetNVSEVersion' not found"

The game itself runs fine outside of this issue, but obviously I'm unable to install any mods that require NVSE to function properly. 

I'm not using any mod organizers currently, just installing xNVSE manually. All the files are in the correct folder, I'm using a fresh install of New Vegas, and I'm running the NVSE Loader as admin so I'm at a loss for what the root of the problem is.

**Comment by MohamedSaif44** [comment]
this issue exist only in latest version(6.2.8),the previous version works fine,so is there any new requirements??

**Comment by MohamedSaif44** [comment]
well it seems that's my fault,cause i made fallout.ini a read-only(can't remember why),and i think Nexus mod manager latest version need to modify it.something related to archive list.hope this helps.
