### ISSUE TITLE
assigning the output of Call to an array will not compile

### ISSUE THREAD

**Issue by adriant1978** [xNVSE/NVSE#72]
Such as, attempting to compile **fnShuffle** and **SomeOtherScript** from the [wiki page about UDFs](https://geckwiki.com/index.php?title=User_Defined_Function):

```
SCRIPTS: Script 'SomeOtherScript', line 9:
Invalid operands for operator :=
```
Using xNVSE 6.2.3 and GECK Extender 0.36

Plugin containing **fnShuffle** and **SomeOtherScript** as copied from wiki page:
[CallUDFArray.zip](https://github.com/xNVSE/NVSE/files/7190710/CallUDFArray.zip)

**Comment by korri123** [comment]
[nvse_editor_1_4.zip](https://github.com/xNVSE/NVSE/files/7190729/nvse_editor_1_4.zip)
Thanks for the report, will be fixed in next update. Here's a DLL containing the fix which you may use.
