### ISSUE TITLE
Why is there suddenly a limit on using In-line variable declaration?

### ISSUE THREAD

**Issue by KirkH420** [xNVSE/NVSE#74]
After I updated 2 days ago, my scripts in my project broke.

It was the fact that I'd taken up the habit of using In-line variable declaration but apparently you guys now have some sort of limit on them now. Now I can only use a handful of inline declarations and then the NVSE Compiler (not Script Compiler) will tell me "Unable to resolve variable type [VarName]" I reverted to the previous version of xNVSE and added 20 more in-line variable declarations with no issue. 

Was wondering what is the reason for this limit and also what is that number set to?

Oh well, not a real problem, I'll just declare them at the top of the script like usual, this was just allowing a bit of text reduction. Like, as in if i'm only going to use a variable once, why waste the line space to type it in two places instead of just once....

**Comment by korri123** [comment]
Fixed with https://github.com/xNVSE/NVSE/commit/2a77996c6f87b173df65633882dffbb17dae600c
