### ISSUE TITLE
Issue with testexpr

### ISSUE THREAD

**Issue by DRSSX4756** [xNVSE/NVSE#8]
This line:
if testexpr arOp["ValTgt"] := athisOp["DynOr"][1]

returns true when aThisOp doesn't contain the key "DynOr", and clearly shouldn't

**Comment by DRSSX4756** [comment]
To further explore this I set up the following test:

`		if testexpr iVal := aTest["bleh"][0]
			print "succ assign to int of non-existing array in stringmap"
		else
			print "fail 1"
		endif
		if testexpr rVar2 := aTest["bleh"][0]
			print "succ assign to ref of non-existing array in stringmap"
		else
			print "fail 2"
		endif
		if testexpr svKey := aTest["bleh"][0]
			print "succ assign to string var of non-existing array in stringmap"
		else
			print "fail 3"
		endif
		let aTest2 := ar_construct "stringmap"
		if testexpr aTest2["bloh"] := aTest["bleh"][0]
			print "succ assign to sMap element of non-existing array in stringmap"
		else
			print "fail 4"
		endif`

The readout shows that testexpr correctly fails for the assignation to the int and ref vars, but succeeds for the assignation to the string var and stringmap element. A little weird that that should make a difference, because it's the right-hand side of the expression that should throw the error.

**Comment by korri123** [comment]
Fixed in https://github.com/xNVSE/NVSE/commit/3b24de28abc57479228a5159aa9b62fb1917c7c4
